//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSite.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BId { get; set; }
        public System.DateTime Time { get; set; }
        public int UId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
    }
}
